### ISSUE TITLE
use monotically increasing values for sensors

### ISSUE THREAD

**Issue by perarnau** [anlsys/nrm-extra#10]
Having events report instantaneous sensor values was a design mistake, as a loss of message might make the current state of the system difficult to asses.

As a result, all reported values should be changed to report an increasing counter since beginning of execution. A good example is power readings: we should just send the energy since boot instead.

**Comment by jlnav** [comment]
I believe this was closed by #13 , although for the Variorum utility we currently only have wattage available to report, not energy. We should discuss this requirement with them.
